import Mathlib.Probability.HasCondDistrib
import Mathlib.Probability.HasLaw
import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.Probability.Distributions.Gaussian.Multivariate
import Mathlib.Analysis.Convex.Hull
import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Probability.Distributions.Gaussian.Real
import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
import Mathlib.Probability.Process.HittingTime
import Mathlib.MeasureTheory.MeasurableSpace.Constructions

/-! # Standalone extraction for `COLT83.gw_le_card`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee (`scripts/make-challenges.py`), with the LML declarations the
statement rests on vendored in below, so that this file is self-contained over Mathlib
(its transitive imports resolve to Mathlib and Lean core only). -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace ProbabilityTheory
end ProbabilityTheory
namespace COLT83
end COLT83

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Algorithm ═══
-- The declarations of https://github.com/LeanMachineLearning/LML that the statement rests on,
-- copied verbatim (Apache 2.0, Authors: Rémy Degenne, Paulo Rauber) so that this file's imports
-- bottom out in Mathlib. Comparator checks each constant is *identical* to the LML package's.
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓐 𝓨 Ω : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- A stochastic, sequential algorithm. -/
structure Algorithm (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] where
  /-- Policy or sampling rule: distribution of the next action. -/
  policy : (n : ℕ) → Kernel (Iic n → 𝓐 × 𝓨) 𝓐
  /-- The policy is a Markov kernel. -/
  [h_policy : ∀ n, IsMarkovKernel (policy n)]
  /-- Distribution of the first action. -/
  p0 : Measure 𝓐
  /-- The first action distribution is a probability measure. -/
  [hp0 : IsProbabilityMeasure p0]

instance (alg : Algorithm 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) := alg.h_policy n
instance (alg : Algorithm 𝓐 𝓨) : IsProbabilityMeasure alg.p0 := alg.hp0

/-- A stochastic environment. -/
structure Environment (𝓐 𝓨 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨] where
  /-- Distribution of the next observation as function of the past history. -/
  feedback : (n : ℕ) → Kernel ((Iic n → 𝓐 × 𝓨) × 𝓐) 𝓨
  /-- The feedback kernels are Markov kernels. -/
  [h_feedback : ∀ n, IsMarkovKernel (feedback n)]
  /-- Distribution of the first observation given the first action. -/
  ν0 : Kernel 𝓐 𝓨
  /-- The initial observation kernel is a Markov kernel. -/
  [hp0 : IsMarkovKernel ν0]

instance (env : Environment 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.feedback n) := env.h_feedback n
instance (env : Environment 𝓐 𝓨) : IsMarkovKernel env.ν0 := env.hp0

section IsAlgEnvSeq

variable {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {alg : Algorithm 𝓐 𝓨} {env : Environment 𝓐 𝓨}
    {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence up to time `n`. -/
def history (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Iic n → 𝓐 × 𝓨 :=
  fun i ↦ (A i ω, Y i ω)

section IsAlgEnvSeq


/-- An algorithm-environment sequence: a sequence of actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (alg : Algorithm 𝓐 𝓨) (env : Environment 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The first action has the correct law. -/
  hasLaw_action_zero : HasLaw (fun ω ↦ (A 0 ω)) alg.p0 P
  /-- The first feedback has the correct conditional distribution. -/
  hasCondDistrib_feedback_zero : HasCondDistrib (Y 0) (A 0) env.ν0 P
  /-- The next action has the correct conditional distribution given the history. -/
  hasCondDistrib_action n :
    HasCondDistrib (A (n + 1)) (history A Y n) (alg.policy n) P
  /-- The next feedback has the correct conditional distribution given the history and
  next action. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y (n + 1)) (fun ω ↦ (history A Y n ω, A (n + 1) ω))
      (env.feedback n) P

end IsAlgEnvSeq

end IsAlgEnvSeq

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StationaryEnv ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓐 𝓨 : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨}

/-- An oblivious environment, in which the distribution of the next feedback depends only on
the last action, but in a possibly time-dependent manner. -/
@[simps]
def obliviousEnv (ν : ℕ → Kernel 𝓐 𝓨) [∀ n, IsMarkovKernel (ν n)] : Environment 𝓐 𝓨 where
  feedback n := (ν (n + 1)).prodMkLeft _
  ν0 := ν 0

/-- A stationary environment, in which the distribution of the next feedback depends only on the
last action. -/
def stationaryEnv (ν : Kernel 𝓐 𝓨) [IsMarkovKernel ν] : Environment 𝓐 𝓨 := obliviousEnv fun _ ↦ ν

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Deterministic ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning
variable {𝓐 𝓨 : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨}

/-- A deterministic algorithm, which chooses the action given by the function `nextAction`. -/
@[simps]
noncomputable
def detAlgorithm (nextA : (n : ℕ) → (Iic n → 𝓐 × 𝓨) → 𝓐)
    (h_next : ∀ n, Measurable (nextA n)) (action0 : 𝓐) :
    Algorithm 𝓐 𝓨 where
  policy n := Kernel.deterministic (nextA n) (h_next n)
  p0 := Measure.dirac action0

end Learning
end

-- ═══ Mathlib.GaussianWidth ═══
section
open MeasureTheory
open scoped RealInnerProductSpace
namespace ProbabilityTheory
variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E] {mE : MeasurableSpace E}

/-- Gaussian width of the set `K` with respect to the measure `μ`:
`∫ ξ, sup_{x ∈ K} ⟪x, ξ⟫ ∂μ`. -/
noncomputable def gaussianWidth (K : Set E) (μ : Measure E) : ℝ :=
  ∫ ξ, ⨆ x : K, ⟪(x : E), ξ⟫ ∂μ

end ProbabilityTheory
end

-- ═══ MXJ2026.Width ═══
section
open MeasureTheory ProbabilityTheory Real
open scoped RealInnerProductSpace
namespace COLT83
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The design matrix `x xᵀ` of a point `x`. -/
def outerSelf (x : EuclideanSpace ℝ ι) : Matrix ι ι ℝ :=
  Matrix.vecMulVec (WithLp.ofLp x) (WithLp.ofLp x)

/-- The set of design matrices of `𝒳`: the convex hull of `{x xᵀ : x ∈ 𝒳}`, that is the set of
matrices `∑ λ_x x xᵀ` for `λ` a finitely supported probability distribution on `𝒳`. -/
def designSet (𝒳 : Set (EuclideanSpace ℝ ι)) : Set (Matrix ι ι ℝ) :=
  convexHull ℝ (outerSelf '' 𝒳)

/-- Gaussian width of the set `K` for the matrix `A`: `E[sup_{x ∈ K} ⟪x, A^{-1/2} g⟫]` for
`g ~ N(0, I)`, that is the Gaussian width of `K` for the centered Gaussian measure with covariance
`A⁻¹` (meaningful for `A` positive definite). -/
noncomputable def gwMat (K : Set (EuclideanSpace ℝ ι)) (A : Matrix ι ι ℝ) : ℝ :=
  gaussianWidth K (multivariateGaussian 0 A⁻¹)

/-- The Gaussian width term `w(𝒳)` of the action set `𝒳`: the infimum of `gwMat 𝒳 A` over the
positive definite design matrices `A` of `𝒳`. -/
noncomputable def gw (𝒳 : Set (EuclideanSpace ℝ ι)) : ℝ :=
  ⨅ A : {A : Matrix ι ι ℝ // A ∈ designSet 𝒳 ∧ A.PosDef}, gwMat 𝒳 A

end COLT83
end

-- ═══ MXJ2026.WidthBounds ═══
section
open MeasureTheory ProbabilityTheory Real
namespace COLT83
variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- **Proposition 4 (i)**: the Gaussian width term of a spanning compact action set in `ℝ^d` is at
most `d`. -/
theorem gw_le_card (𝒳 : Set (EuclideanSpace ℝ ι)) (h𝒳 : IsCompact 𝒳) (hne : 𝒳.Nonempty)
    (hspan : Submodule.span ℝ 𝒳 = ⊤) :
    gw 𝒳 ≤ Fintype.card ι := sorry

end COLT83
end
