import Mathlib.Probability.HasCondDistrib
import Mathlib.Probability.HasLaw
import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.MeasureTheory.MeasurableSpace.Embedding
import Mathlib.Probability.Process.HittingTime
import Mathlib.Probability.Distributions.Gaussian.Real
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.MeasureTheory.Function.SpecialFunctions.Inner
import Mathlib.Analysis.Complex.ExponentialBounds
import Mathlib.Analysis.Matrix.Order
import Mathlib.Probability.Distributions.Gaussian.Fernique
import Mathlib.Probability.Distributions.Gaussian.Multivariate
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.LinearAlgebra.Matrix.PosDef
import Mathlib.Analysis.InnerProductSpace.Continuous
import Mathlib.Data.Fintype.Order
import Mathlib.Analysis.Calculus.Gradient.Basic
import Mathlib.Algebra.BigOperators.Field
import Mathlib.Analysis.SpecialFunctions.Log.Deriv
import Mathlib.Algebra.Order.BigOperators.Ring.Finset
import Mathlib.Analysis.Convex.Integral
import Mathlib.MeasureTheory.Integral.IntervalIntegral.FundThmCalculus
import Mathlib.Analysis.SpecialFunctions.Trigonometric.Deriv
import Mathlib.Analysis.Calculus.MeanValue
import Mathlib.Analysis.Calculus.ContDiff.Comp
import Mathlib.Probability.Moments.SubGaussian
import Mathlib.Probability.Independence.Integration
import Mathlib.Probability.Independence.InfinitePi
import Mathlib.InformationTheory.KullbackLeibler.Basic
import Mathlib.MeasureTheory.Measure.Decomposition.Lebesgue
import Mathlib.Analysis.Convex.Caratheodory
import Mathlib.Geometry.Convex.ConvexSpace.CompactSpaceStdSimplex
import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
import Mathlib.Topology.Algebra.Ring.Real
import Mathlib.Analysis.Calculus.Deriv.Slope
import Mathlib.Probability.Independence.Basic
import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.MeasureTheory.Integral.Prod
import Mathlib.Probability.Kernel.Composition.IntegralCompProd
import Mathlib.Probability.Distributions.Gaussian.HasGaussianLaw.Basic
import Mathlib.Probability.Distributions.Gaussian.HasGaussianLaw.Independence
import Mathlib.Basic.Real.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Analysis.Real.Pi.Bounds
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.Data.Matrix.ColumnRowPartitioned
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Algebra.BigOperators.Ring.Finset

/-! # Standalone extraction for `Maiti2026Power.exists_isPAC_blockBallSet`
Definitions are copied verbatim; theorem proofs are replaced by `sorry`.
Auto-generated by Referee (`scripts/make-challenges.py`), with the LML declarations the
statement rests on vendored in below, so that this file is self-contained over Mathlib
(its transitive imports resolve to Mathlib and Lean core only). -/

set_option quotPrecheck false

-- Namespace stubs (so later `open`s resolve).
namespace MeasureTheory
end MeasureTheory
namespace ProbabilityTheory
end ProbabilityTheory
namespace Finset
end Finset
namespace Learning
end Learning
namespace Learning.IdentAlg
end Learning.IdentAlg
namespace Learning.LinearBandit
end Learning.LinearBandit
namespace Maiti2026Power
end Maiti2026Power
namespace Real
end Real

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Algorithm ═══
-- The declarations of https://github.com/LeanMachineLearning/LML that the statement rests on,
-- copied verbatim (Apache 2.0, Authors: Rémy Degenne, Paulo Rauber) so that this file's imports
-- bottom out in Mathlib. Comparator checks each constant is *identical* to the LML package's.
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 Ω : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨} {mΩ : MeasurableSpace Ω}

/-- One round of interaction: an observation, then an action, then a feedback. -/
abbrev Round (𝓞 𝓐 𝓨 : Type*) := 𝓞 × 𝓐 × 𝓨

/-- History of `n` complete rounds; `n = 0` is the empty history. -/
abbrev Hist (𝓞 𝓐 𝓨 : Type*) (n : ℕ) := Fin n → Round 𝓞 𝓐 𝓨

/-- A stochastic, sequential algorithm.
At each round, it sees an observation in `𝓞`, then takes an action in `𝓐`, and finally receives
feedback in `𝓨`. The action is a random function of the past rounds and the current observation. -/
@[ext]
structure Algorithm (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the action of round `n` given the past rounds and the current observation. -/
  policy : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n × 𝓞) 𝓐
  /-- The policy is a Markov kernel. -/
  [isMarkovKernel_policy : ∀ n, IsMarkovKernel (policy n)]

instance (alg : Algorithm 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (alg.policy n) :=
  alg.isMarkovKernel_policy n

/-- A stochastic environment.
At each round, an observation is drawn prior to the algorithm taking an action. Then the environment
provides feedback based on the observation and the action. -/
@[ext]
structure Environment (𝓞 𝓐 𝓨 : Type*) [MeasurableSpace 𝓞] [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    where
  /-- Law of the observation of round `n` given the past rounds. -/
  obs : (n : ℕ) → Kernel (Hist 𝓞 𝓐 𝓨 n) 𝓞
  /-- Law of the feedback of round `n` given the past rounds, the observation and the action. -/
  feedback : (n : ℕ) → Kernel ((Hist 𝓞 𝓐 𝓨 n × 𝓞) × 𝓐) 𝓨
  /-- The observation kernel is a Markov kernel. -/
  [isMarkovKernel_obs : ∀ n, IsMarkovKernel (obs n)]
  /-- The feedback kernel is a Markov kernel. -/
  [isMarkovKernel_feedback : ∀ n, IsMarkovKernel (feedback n)]

instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.obs n) := env.isMarkovKernel_obs n
instance (env : Environment 𝓞 𝓐 𝓨) (n : ℕ) : IsMarkovKernel (env.feedback n) :=
  env.isMarkovKernel_feedback n

section IsAlgEnvSeq

variable {O : ℕ → Ω → 𝓞} {A : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨}
    {alg : Algorithm 𝓞 𝓐 𝓨} {env : Environment 𝓞 𝓐 𝓨}
    {P : Measure Ω} [IsFiniteMeasure P] {N : ℕ}

/-- History of the algorithm-environment sequence before time `n`: the rounds at
times `0, ..., n - 1`. -/
def history (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (n : ℕ) (ω : Ω) : Hist 𝓞 𝓐 𝓨 n :=
  fun i ↦ (O i ω, A i ω, Y i ω)

/-- An algorithm-environment sequence: a sequence of observations, actions and feedbacks generated
by an algorithm interacting with an environment. -/
structure IsAlgEnvSeq
    (O : ℕ → Ω → 𝓞) (A : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (alg : Algorithm 𝓞 𝓐 𝓨) (env : Environment 𝓞 𝓐 𝓨)
    (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The observation sequence is measurable. -/
  measurable_obs n : Measurable (O n) := by fun_prop
  /-- The action sequence is measurable. -/
  measurable_action n : Measurable (A n) := by fun_prop
  /-- The feedback sequence is measurable. -/
  measurable_feedback n : Measurable (Y n) := by fun_prop
  /-- The observation at time `n` has the correct conditional distribution given the history. -/
  hasCondDistrib_obs n :
    HasCondDistrib (O n) (history O A Y n) (env.obs n) P
  /-- The action at time `n` has the correct conditional distribution given the history and the
  observation at time `n`. -/
  hasCondDistrib_action n :
    HasCondDistrib (A n) (fun ω ↦ (history O A Y n ω, O n ω)) (alg.policy n) P
  /-- The feedback at time `n` has the correct conditional distribution given the history, the
  observation and the action at time `n`. -/
  hasCondDistrib_feedback n :
    HasCondDistrib (Y n) (fun ω ↦ ((history O A Y n ω, O n ω), A n ω)) (env.feedback n) P

end IsAlgEnvSeq

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.StationaryEnv ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨}

/-- An oblivious environment without observations, in which the distribution of the next feedback
depends only on the last action, but in a possibly time-dependent manner. -/
@[simps]
noncomputable
def obliviousEnv (ν : ℕ → Kernel 𝓐 𝓨) [∀ n, IsMarkovKernel (ν n)] : Environment Unit 𝓐 𝓨 where
  obs _ := Kernel.const _ (Measure.dirac ())
  feedback n := (ν n).prodMkLeft _

/-- A stationary environment without observations, in which the distribution of the next feedback
depends only on the last action. -/
noncomputable
def stationaryEnv (ν : Kernel 𝓐 𝓨) [IsMarkovKernel ν] : Environment Unit 𝓐 𝓨 :=
  obliviousEnv fun _ ↦ ν

end Learning
end

-- ═══ vendored from LML: LeanMachineLearning.SequentialLearning.Deterministic ═══
section
open MeasureTheory ProbabilityTheory Filter Real Finset
open scoped ENNReal NNReal
namespace Learning

variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐}
  {m𝓨 : MeasurableSpace 𝓨}

/-- A deterministic algorithm, which chooses the action given by the function `nextA`.
The initial action is `fun o ↦ nextA 0 (default, o)`. -/
@[simps]
noncomputable
def detAlgorithm (nextA : (n : ℕ) → (Hist 𝓞 𝓐 𝓨 n × 𝓞) → 𝓐)
    (h_next : ∀ n, Measurable (nextA n)) :
    Algorithm 𝓞 𝓐 𝓨 where
  policy n := Kernel.deterministic (nextA n) (h_next n)

end Learning
end

-- ═══ Mathlib.MeasureTheory.MeasurableSpace.Sigma ═══
section
open MeasurableSpace
variable {α γ : Type*} {β : α → Type*} [∀ a, MeasurableSpace (β a)] [MeasurableSpace γ]

/-- A function on a sigma type is measurable if all its restrictions to the fibers are. -/
lemma measurable_sigma_of_measurable_comp_mk {f : (Σ a, β a) → γ}
    (h : ∀ a, Measurable (f ∘ Sigma.mk a)) : Measurable f := sorry

end

-- ═══ LeanMachineLearning.StoppedHistory ═══
section
open MeasureTheory ProbabilityTheory Finset
open scoped ENat
namespace Learning
variable {𝓞 𝓐 𝓨 : Type*} {m𝓞 : MeasurableSpace 𝓞} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- The stopping time of the stopping rule `S` on the action and feedback processes `X`, `Y`:
the number of rounds played, that is the first `n` such that the history of the first `n` rounds
belongs to `S` (`⊤` if there is none). -/
noncomputable def stoppingTime (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (S : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)) : Ω → ℕ∞ :=
  hittingAfter (fun n ω ↦ (⟨n, history O X Y n ω⟩ : Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)) S 0

/-- The history of the first `τ ω` rounds, as a history of variable length (of length `0` if
`τ ω = ⊤`). -/
noncomputable def stoppedHist (O : ℕ → Ω → 𝓞) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (τ : Ω → ℕ∞)
    (ω : Ω) :
    Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n :=
  ⟨(τ ω).toNat, history O X Y _ ω⟩

variable {O : ℕ → Ω → 𝓞} {X : ℕ → Ω → 𝓐} {Y : ℕ → Ω → 𝓨} {S : Set (Σ n : ℕ, Hist 𝓞 𝓐 𝓨 n)} {τ : Ω → ℕ∞} {ω : Ω} {n M : ℕ}
end Learning
end

-- ═══ LeanMachineLearning.IdentAlg ═══
section
open MeasureTheory ProbabilityTheory
open scoped ENat
universe u
namespace Learning
variable {𝓐 𝓨 𝓞 : Type*} {m𝓐 : MeasurableSpace 𝓐} {m𝓨 : MeasurableSpace 𝓨} {m𝓞 : MeasurableSpace 𝓞} {Ω : Type*} {mΩ : MeasurableSpace Ω}

/-- An identification algorithm with outputs in `𝓞`: a sampling rule `alg`, a stopping rule
`stop` (`stop n h`: stop after `n` rounds when their history is `h`) and an output rule `output`
(the distribution of the output given the history of the `n` rounds played), which is a
probability measure on every history at which the algorithm stops. -/
structure IdentAlg (𝓐 𝓨 𝓞 : Type*) [MeasurableSpace 𝓐] [MeasurableSpace 𝓨]
    [MeasurableSpace 𝓞] where
  /-- The sampling rule. -/
  alg : Algorithm Unit 𝓐 𝓨
  /-- The stopping rule: `stop n h` means that the algorithm stops after `n` rounds when the
  history of these rounds is `h`. -/
  stop : (n : ℕ) → Hist Unit 𝓐 𝓨 n → Prop
  /-- The stopping rule is measurable. -/
  measurableSet_stop : ∀ n, MeasurableSet {h | stop n h}
  /-- The output rule: distribution of the output given the history of the `n` rounds played. -/
  output : (n : ℕ) → Kernel (Hist Unit 𝓐 𝓨 n) 𝓞
  /-- The output kernels are s-finite (so that the joint law of history and output is a
  composition-product). -/
  [isSFiniteKernel_output : ∀ n, IsSFiniteKernel (output n)]
  /-- The output rule is a probability measure on every history at which the algorithm stops. -/
  [isProbabilityMeasure_output : ∀ n h, stop n h → IsProbabilityMeasure (output n h)]

namespace IdentAlg
variable (A : IdentAlg 𝓐 𝓨 𝓞) (O : ℕ → Ω → Unit) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)

/-- The stopping rule of `A` as a set of histories of variable length. -/
def stopSet : Set (Σ n : ℕ, Hist Unit 𝓐 𝓨 n) := {h | A.stop h.1 h.2}

/-- The stopping time of `A` on the observation, action and feedback processes `O`, `X`, `Y`: the
number of rounds
played, that is the first `n` such that the stopping rule fires on the history of the first `n`
rounds (`⊤` if it never does). It is the stopping time `Learning.stoppingTime` of the stopping
rule `A.stopSet`. -/
noncomputable def stoppingTime : Ω → ℕ∞ := Learning.stoppingTime O X Y A.stopSet

/-- The history of the rounds played by `A`, as a history of variable length (of length `0` if
`A` never stops): the history stopped at `A.stoppingTime O X Y`. -/
noncomputable def stoppedHist : Ω → Σ n : ℕ, Hist Unit 𝓐 𝓨 n :=
  Learning.stoppedHist O X Y (A.stoppingTime O X Y)

/-- The output rule of `A` as a single kernel on histories of variable length. -/
noncomputable def outputKernel : Kernel (Σ n : ℕ, Hist Unit 𝓐 𝓨 n) 𝓞 where
  toFun h := A.output h.1 h.2
  measurable' := measurable_sigma_of_measurable_comp_mk fun n ↦ (A.output n).measurable

/-- `(O, X, Y, out)` is a *run* of the identification algorithm `A` in the environment `env` on
the probability space `(Ω, P)`: the observation, action and feedback processes `O`, `X`, `Y` form
an algorithm-environment sequence for the sampling rule `A.alg` and `env`, and the output `out` has
conditional law `A.output` given the history at the stopping time. -/
structure IsRun (env : Environment Unit 𝓐 𝓨) (O : ℕ → Ω → Unit) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨)
    (out : Ω → 𝓞) (P : Measure Ω) [IsFiniteMeasure P] : Prop where
  /-- The actions and feedbacks are generated by the sampling rule in the environment. -/
  isAlgEnvSeq : IsAlgEnvSeq O X Y A.alg env P
  /-- The output is drawn from the output rule applied to the history at the stopping time. -/
  hasCondDistrib_output : HasCondDistrib out (A.stoppedHist O X Y) A.outputKernel P

/-- `A` is *PAC at level `δ`* for the family of environments `env : Θ → Environment Unit 𝓐 𝓨` and
the goodness predicate `good : Θ → 𝓞 → Prop` if, for every `θ` and every run of `A` in `env θ` on
a probability space `(Ω, P)`, the output is `good θ` with probability at least `1 - δ`. -/
def IsPAC {Θ : Type*} (env : Θ → Environment Unit 𝓐 𝓨) (good : Θ → 𝓞 → Prop) (δ : ℝ) : Prop :=
  ∀ θ, ∀ {Ω : Type u} {_mΩ : MeasurableSpace Ω} (P : Measure Ω) [IsProbabilityMeasure P]
    (O : ℕ → Ω → Unit) (X : ℕ → Ω → 𝓐) (Y : ℕ → Ω → 𝓨) (out : Ω → 𝓞),
    A.IsRun (env θ) O X Y out P →
    1 - δ ≤ P.real {ω | good θ (out ω)}

/-- `A` is a *fixed-budget* algorithm with budget `T` if its stopping rule is "stop after exactly
`T` rounds". -/
def IsFixedBudget (T : ℕ) : Prop := A.stop = fun n _ ↦ n = T

end IdentAlg
end Learning
end

-- ═══ LeanMachineLearning.LinearBandit ═══
section
open MeasureTheory ProbabilityTheory
open scoped RealInnerProductSpace NNReal
universe u
namespace Learning.LinearBandit
variable {E : Type u} [NormedAddCommGroup E] [InnerProductSpace ℝ E] [MeasurableSpace E] [OpensMeasurableSpace E]

/-- Reward kernel of the linear Gaussian bandit on `𝒳` with reward vector `θ`: playing `x` gives an
observation with law `N(⟪x, θ⟫, 1)`. -/
noncomputable def linearGaussianKernel (𝒳 : Set E) (θ : E) : Kernel 𝒳 ℝ where
  toFun x := gaussianReal ⟪(x : E), θ⟫ 1
  measurable' := by
    change Measurable (gaussianReal.uncurry ∘ fun x : 𝒳 ↦ (⟪(x : E), θ⟫, (1 : ℝ≥0)))
    exact measurable_gaussianReal.comp (by fun_prop)

/-- The linear Gaussian environment on the action set `𝒳` with reward vector `θ`: the stationary
environment with reward kernel `linearGaussianKernel 𝒳 θ`.

The Markov-kernel argument of `stationaryEnv` is given inline rather than through the instance
above: the nested proof of an exposed `def` becomes a public auxiliary constant, whereas the proof
inside an instance (a theorem) becomes a module-private one, which the standalone comparator
challenges (`comparator/`) could not reproduce. -/
noncomputable def linearGaussianEnv (𝒳 : Set E) (θ : E) : Environment Unit 𝒳 ℝ :=
  @stationaryEnv _ _ _ _ (linearGaussianKernel 𝒳 θ)
    ⟨fun _ ↦ inferInstanceAs (IsProbabilityMeasure (gaussianReal _ 1))⟩

/-- Simple regret of the arm `x` for the reward vector `θ` on the action set `𝒳`:
`sup_{y ∈ 𝒳} ⟪y, θ⟫ - ⟪x, θ⟫`. -/
noncomputable def simpleRegret (𝒳 : Set E) (θ x : E) : ℝ :=
  (⨆ y : 𝒳, ⟪(y : E), θ⟫) - ⟪x, θ⟫

/-- An identification algorithm (with actions in `𝒳`, real observations and recommendations in
`𝒳`) is `(ε, δ)`-PAC on `𝒳` if for every reward vector `θ`, run against the linear Gaussian
environment `linearGaussianEnv 𝒳 θ`, its recommendation has simple regret at most `ε` with
probability at least `1 - δ`, for every run on every probability space `Ω` in the universe of `E`
(the universe in which runs of `A` can be constructed, see `IdentAlg.exists_isRun`). -/
def IsPAC (𝒳 : Set E) (A : IdentAlg 𝒳 ℝ 𝒳) (ε δ : ℝ) : Prop :=
  A.IsPAC.{u} (linearGaussianEnv 𝒳) (fun θ x ↦ simpleRegret 𝒳 θ x ≤ ε) δ

end Learning.LinearBandit
end

-- ═══ MXJ2026.StructuredSets ═══
section
namespace Maiti2026Power
variable (ι : Type*) [Fintype ι]
variable {ι}

/-- The block-ball set in `ℝ^(Fin k × Fin d)`: the union over the `k` blocks `i` of the unit balls
`{x : ‖x‖ ≤ 1, x supported on block i}`. -/
def blockBallSet (k d : ℕ) : Set (EuclideanSpace ℝ (Fin k × Fin d)) :=
  {x | ‖x‖ ≤ 1 ∧ ∃ i, ∀ j, j ≠ i → ∀ l, x (j, l) = 0}

end Maiti2026Power
end

-- ═══ MXJ2026.Separation ═══
section
open MeasureTheory ProbabilityTheory Real Learning Learning.LinearBandit Finset
open scoped RealInnerProductSpace
namespace Maiti2026Power

/-- **Theorem 7, adaptive upper bound**: for `k ≥ 1`, `ε ∈ (0, 1]` and `δ ∈ (0, 1)`, there is an
(adaptive) `(ε, δ)`-PAC identification algorithm on the block-ball set of `ℝ^{kd}` with budget
`T ≤ 2·10⁶ (kd log(8k/δ) + d²) / ε²`. -/
theorem exists_isPAC_blockBallSet (k d : ℕ) (hk : 1 ≤ k) {ε δ : ℝ} (hε : ε ∈ Set.Ioc 0 1)
    (hδ : δ ∈ Set.Ioo 0 1) :
    ∃ T : ℕ, (T : ℝ) ≤ 2000000 * (k * d * log (8 * k / δ) + (d : ℝ) ^ 2) / ε ^ 2 ∧
      ∃ A : IdentAlg (blockBallSet k d) ℝ (blockBallSet k d), A.IsFixedBudget T ∧
        IsPAC (blockBallSet k d) A ε δ := sorry

end Maiti2026Power
end
